--DDL
CREATE DATABASE T_Peoples;

USE T_Peoples;

CREATE TABLE Funcionarios (
	IdFuncionario	INT PRIMARY KEY IDENTITY, 
	Nome			VARCHAR(200) NOT NULL,
	Sobrenome		VARCHAR(200) NOT NULL 
);

CREATE TABLE TipoUsuario (
	IdTipoUsuario	INT PRIMARY KEY IDENTITY,
	Titulo			VARCHAR (200) NOT NULL
);

CREATE TABLE Usuarios (
	IdUsuario		INT PRIMARY KEY IDENTITY,
	Email			VARCHAR (255) NOT NULL UNIQUE,
	Senha			VARCHAR (255) NOT NULL,
	IdTipoUsuario	INT FOREIGN KEY REFERENCES TipoUsuario (IdTipoUsuario)
);

ALTER TABLE Funcionarios 
ALTER COLUMN DataNascimento	DATETIME;


DROP TABLE Usuarios;

DROP TABLE TipoUsuario;


